CREATE DATABASE LESSONSDB

USE LESSONSDB

-- თეიბლის შექმნა
CREATE TABLE PERSONS(
FIRSTNAME VARCHAR(30),
LASTNAME VARCHAR(40),
ADDRES VARCHAR(50),
)

--თეიბლიდან ინფორმაციის ამოშლა
TRUNCATE TABLE PEROSNS
  
--თეიბლში დამატება
ALTER TABLE PERSONS
ADD AGE VARCHAR(40);

--თეიბში სვეტის წაშლა
ALTER TABLE PERSONS
DROP COLUMN AGE;


ALTER TABLE PERSONS
ADD NAMELIST VARCHAR(40);

--სვეტის შეცვლა INT ტიპად
ALTER TABLE PERSONS
ALTER COLUMN FIRSTNAME int;


ALTER TABLE PERSONS
ALTER COLUMN LASTNAME INT;

