CREATE DATABASE LESSONSDB

USE LESSONSDB
  
CREATE TABLE PERSONS(
FIRSTNAME VARCHAR(30),
LASTNAME VARCHAR(40),
ADDRES VARCHAR(50),
)

ALTER TABLE PERSONS
ADD AGE VARCHAR(40);

ALTER TABLE PERSONS
DROP COLUMN AGE;

ALTER TABLE PERSONS
ADD NAMELIST VARCHAR(40);

ALTER TABLE PERSONS
ALTER COLUMN FIRSTNAME int;

ALTER TABLE PERSONS
ALTER COLUMN LASTNAME INT;
