CREATE DATABASE JUBADB
USE JUBADB

CREATE TABLE KOGUASHVILI(
ID VARCHAR (20),
SAXELI VARCHAR (20),
GVARI VARCHAR (20),
QALAQI VARCHAR (20),
MISAMARTI VARCHAR (20),
)

INSERT INTO KOGUASHVILI(
ID,
SAXELI,
GVARI,
QALAQI,
MISAMARTI
) VALUES(
1,
'VALODIA',
'AMILAXVARI',
'LONDONI',
'DIGOMI'
)

INSERT INTO KOGUASHVILI VALUES(2,'MATE', 'AMIREJIBI', 'BATUMI', 'AGMASHENEBELI')

INSERT INTO KOGUASHVILI (
SAXELI,
GVARI,
QALAQI
) VALUES(
'LANA',
'MIKAUTADZE',
'KUTAISI'
)

UPDATE KOGUASHVILI
SET AGE = 33
WHERE ID = 104;

SET IDENTITY_INSERT dbo.KOGUASHVILI OFF;

DELETE FROM KOGUASHVILI
WHERE ID = 3;


ALTER TABLE KOGUASHVILI
DROP COLUMN ID

ALTER TABLE KOGUASHVILI
ADD  ID INT IDENTITY(100,2) PRIMARY KEY
ALTER TABLE KOGUASHVILI
ADD  AGE VARCHAR(20)

ALTER TABLE KOGUASHVILI
DROP COLUMN AGE

ALTER TABLE KOGUASHVILI
ADD AGE INT CHECK(AGE>=18) 

UPDATE KOGUASHVILI
SET AGE = 18
WHERE ID = 102;

ALTER TABLE KOGUASHVILI
ADD CONSTRAINT DF_ADDRES DEFAULT 'AVLABRIS 38' FOR MISAMARTI
SET IDENTITY_INSERT KOGUASHVILI ON;

ALTER TABLE KOGUASHVILI
DROP COLUMN SAXELI

ALTER TABLE KOGUASHVILI
ADD SAXELI VARCHAR(20)
UPDATE KOGUASHVILI
SET SAXELI = 'LANA'
WHERE ID = 104

UPDATE KOGUASHVILI
SET SAXELI = 'JEMALI'
WHERE ID = 100

ALTER TABLE KOGUASHVILI
ALTER COLUMN SAXELI VARCHAR(20) NOT NULL

ALTER TABLE KOGUASHVILI
ALTER COLUMN GVARI VARCHAR(20) NOT NULL

CREATE TABLE ORDERS(
ORDERID INT PRIMARY KEY IDENTITY(1,1),
ORDERNUMBERS INT NOT NULL,
PIRADIID INT,
CONSTRAINT FK_PIRADID FOREIGN KEY (PIRADIID) REFERENCES KOGUASHVILI(ID)
);

-- პოულობს ყველა ელემენტს ბაზაში
SELECT * FROM KOGUASHVILI;

-- ითვლის ყველა ელემენტს ბაზაში
SELECT COUNT (*) FROM KOGUASHVILI


SELECT ID FROM KOGUASHVILI
WHERE ID >= 100;

--იპოვის ასაკს რომელიც მეტია ან ტოლია 18-ზე და სახელი შეესაბამება 'ლანა'-ს
SELECT * FROM KOGUASHVILI
WHERE AGE >= 18 AND SAXELI = 'LANA';
